### ISSUE TITLE
Schedule type representation

### ISSUE THREAD

**Issue by j3kestrel** [wildcomputations/budgettool#5]
Presently a schedule is represented as this:
`"schedule":{ "type":"once", "date":"16 March 2016" }`

Replace that with:
`"schedule_type": "once", "schedule_data":{ "date":"16 March 2016" }`

Alternate option:
`"schedule":{"type": "once", "data":{ "date":"16 March 2016" }}`

**Comment by wildcomputations** [comment]
Unclear if we should change the representation in json or just change how the "type" is handled in the scheduler to and from dict functions.
